Repository mozilla/unity-webvr-export, pull requests merged in 2018-02, with the labels that each got.

#138 update supported Unity versions in README; fix a few typos
  README.md
Labels: documentation

#132 fix issues with `{getFrameData,submitFrame} must be called within a VRDisplay.requestAnimationFrame callback.` (fixes issue #65); fix JS errors `Screen position out of view frustum` in Chrome Canary (fixes issue #64)
  Assets/WebGLTemplates/WebVR/webvr.js
Labels: bug

#150 have GIF link to demo; tweak Demo heading
  README.md
Labels: enhancement

#137 Add customization section with instructions to configure GA
  README.md
  docs/customization/adding-ga.md
  docs/customization/images/add-to-index.png
  docs/customization/images/filled-1.png
  docs/customization/images/filled-2.png
  docs/customization/images/new-account.png
  docs/customization/images/setup-done.png
  docs/customization/images/setup-ga.png
  docs/customization/images/terms-of-service.png
Labels: documentation

#163 polish CSS template code (addresses CSS only for issue #104)
  Assets/WebGLTemplates/WebVR/webvr.css
  Build/webvr.css
Labels: enhancement
